import os
from datetime import datetime
from src.quant_a.data_handler import get_historical_data
from src.quant_a.strategy_engine import calculate_performance_metrics, run_buy_and_hold_strategy

def generate_daily_report():
    """
    Automated task to fetch data, calculate metrics, 
    and save a summary report to the data directory.
    """
    ticker = "NVDA"
    today_str = datetime.now().strftime("%Y-%m-%d")
    report_filename = f"data/report_{today_str}.txt"
    
    print(f"[{datetime.now()}] Starting daily report for {ticker}...")
    
    # 1. Fetch data (last 30 days for context)
    data = get_historical_data(ticker, period="1mo")
    
    if data.empty:
        print("Error: No data retrieved.")
        return

    # 2. Run basic analysis
    result_df = run_buy_and_hold_strategy(data)
    sharpe, mdd = calculate_performance_metrics(result_df['Returns'])
    
    current_price = result_df['Price'].iloc[-1]
    daily_return = result_df['Returns'].iloc[-1] * 100

    # 3. Create the report content
    report_content = f"""
==================================================
QUANT RESEARCH DAILY REPORT - {today_str}
==================================================
Asset: {ticker} (NVIDIA Corp)
Status: Market Close
--------------------------------------------------
LATEST METRICS:
- Closing Price: ${current_price:.2f}
- Daily Variation: {daily_return:+.2f}%
- 1-Month Sharpe Ratio: {sharpe}
- 1-Month Max Drawdown: {mdd*100:.2f}%
--------------------------------------------------
Generated by: Finance_git Platform (Automated)
==================================================
"""

    # 4. Save to file
    try:
        with open(report_filename, "w") as f:
            f.write(report_content)
        print(f"Success: Report saved to {report_filename}")
    except Exception as e:
        print(f"File Error: {e}")

if __name__ == "__main__":
    generate_daily_report()